<a href="https://colab.research.google.com/github/RodrigoGuedesDP/Programacion_101/blob/main/Examen_3_Rodrigo_Guedes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Pregunta 1:
a) Crea un array unidimensional que contenga los números primos entre 1 y 50.
b) Convierte el array unidimensional anterior en una matriz de forma (n, 2), donde n es el número adecuado de
filas. Si es necesario, agrega ceros al final del array para completar la matriz.
c) Calcula la suma de cada fila y crea un nuevo array que contenga estos valores.

In [3]:
import numpy as np


# a) funcion para retornar los primos
def es_primo(n):
    if n < 2:
        return False
    return np.all(n % np.arange(2, int(np.sqrt(n)) + 1) != 0)

primos = np.array([n for n in range(1, 51) if es_primo(n)])

# b)
if len(primos) % 2 != 0:
    primos = np.append(primos, 0)
matriz = primos.reshape(-1, 2)

# c)
suma_filas = matriz.sum(axis=1)

print("Array unidimensional de números primos:", primos)
print("Matriz (n, 2):\n", matriz)
print("Suma de cada fila:", suma_filas)


###Pregunta 2:
a) Crea un array bidimensional de forma (4, 4) que contenga números enteros aleatorios entre 1 y 100.
b) Cambia el tipo de datos del array a float64 y divide todos los elementos por 3.7.
c) Calcula y muestra las siguientes propiedades del array resultante:
● Dimensiones (ndim)
● Forma (shape)
● Tamaño total (size)
● Tipo de datos (dtype)


In [5]:
array_bidimensional = np.random.randint(1,101,(4,4))
array_float = array_bidimensional.astype(np.float64)/3.7
print("Dimensiones (ndim):", array_float.ndim)
print("Forma (shape):", array_float.shape)
print("Tamaño total (size):", array_float.size)
print("Tipo de datos (dtype):", array_float.dtype)

Dimensiones (ndim): 2
Forma (shape): (4, 4)
Tamaño total (size): 16
Tipo de datos (dtype): float64


###Pregunta 3:
a) Crea un array x que contenga 100 valores equiespaciados entre -10 y 10.
b) Calcula el valor de la función f(x)=e**(-x**2) para cada elemento de x.
c) Encuentra el valor máximo y mínimo de f(x) y las posiciones en el array donde ocurren

In [9]:
x = np.linspace(-10,10,100)
funcion_x = np.e**(-x**2)
valor_maximo = funcion_x.max()
valor_minimo = funcion_x.min()
posicion_maximo = funcion_x.argmax()
posicion_minimo = funcion_x.argmin()

print(posicion_maximo)
print(posicion_minimo)

49
0


###Pregunta 4: Indexación y Slicing Avanzado
Dado el siguiente array bidimensional:
array = np.arange(1, 101).reshape(10, 10)
a) Extrae un subarray que contenga los elementos en posiciones pares de filas y columnas (es decir, filas y
columnas con índices 0, 2, 4, 6, 8).
b) Reemplaza todos los elementos que son múltiplos de 3 por -1.
c) Utiliza indexación avanzada para extraer todos los números primos del array original y crea un nuevo array
con estos valores.


In [11]:
array = np.arange(1, 101).reshape(10, 10)

sub_array = array[::2,::2]
print(sub_array)
#imprimimos para ver si esta bien el slicing

[[ 1  3  5  7  9]
 [21 23 25 27 29]
 [41 43 45 47 49]
 [61 63 65 67 69]
 [81 83 85 87 89]]


In [ ]:
array_modificado = sub_array.copy()
if array_modificado

### Pregunta 5:
a) Crea tres arrays unidimensionales de longitud 5 con números aleatorios entre 0 y 1.
b) Combina estos arrays para formar una matriz de forma (5, 3).
c) Agrega una columna de unos al principio de la matriz resultante, obteniendo una matriz de forma (5, 4).
d) Reordena las columnas de la matriz para que la columna de unos esté al final.


In [17]:
a = np.random.rand(5,)
b = np.random.rand(5,)
c = np.random.rand(5,)

matriz = np.concatenate([a.reshape(5, 1), b.reshape(5, 1), c.reshape(5, 1)], axis=1)


matriz_unos = np.ones((5, 1))
matriz_con_unos_inicio = np.concatenate([matriz_unos, matriz], axis=1)

matriz_reordenada = np.concatenate([matriz, matriz_unos], axis=1)

print("Matriz inicial (5x3):\n", matriz)
print("Matriz con columna de unos al principio:\n", matriz_con_unos_inicio)
print("Matriz con columna de unos al final:\n", matriz_reordenada)

Matriz inicial (5x3):
 [[0.39899691 0.26747224 0.17190951]
 [0.38943949 0.29700328 0.58376779]
 [0.10369283 0.16201754 0.53155988]
 [0.88325114 0.35260403 0.39336386]
 [0.45900691 0.78524073 0.70900192]]
Matriz con columna de unos al principio:
 [[1.         0.39899691 0.26747224 0.17190951]
 [1.         0.38943949 0.29700328 0.58376779]
 [1.         0.10369283 0.16201754 0.53155988]
 [1.         0.88325114 0.35260403 0.39336386]
 [1.         0.45900691 0.78524073 0.70900192]]
Matriz con columna de unos al final:
 [[0.39899691 0.26747224 0.17190951 1.        ]
 [0.38943949 0.29700328 0.58376779 1.        ]
 [0.10369283 0.16201754 0.53155988 1.        ]
 [0.88325114 0.35260403 0.39336386 1.        ]
 [0.45900691 0.78524073 0.70900192 1.        ]]


###Pregunta 6:
a) Crea una matriz simétrica positiva definida de tamaño 3x3.
b) Calcula sus valores y vectores propios (eigenvalores y eigenvectores).
c) Verifica que la multiplicación de la matriz original por un vector propio es igual al producto del eigenvalor
correspondiente por el vector propio.


In [19]:
#a)
A = np.random.rand(3, 3)
#Multiplicandolo por su transpuesta se
matriz_simetrica = np.dot(A, A.T)

#b)
eigenvalores, eigenvectores = np.linalg.eigh(matriz_simetrica)

#c)




###Pregunta 7:
a) Construye un sistema de ecuaciones lineales con tres ecuaciones y tres incógnitas donde la matriz de
coeficientes es singular (no invertible).
b) Intenta resolver el sistema utilizando np.linalg.solve() y explica el resultado obtenido.


In [20]:
# a)
#Separamos los coeficientes y la matriz de constantes
coeficientes = np.array([[2, 1, -1], [4, 2, -2], [1, 1, -1]])
constantes = np.array([1, 2, 0])

# b) Resolver el sistema usando np.linalg.solve()

solucion = np.linalg.solve(coeficientes, constantes)


# Vemos que sale error porque la matriz de coeficientes (extraida del curso de matetrmatica) no es inversible, lo cual teoricamente se comprueba si su terminante es 0


LinAlgError: Singular matrix

In [21]:
#vemos si su determinante es 0
determinante = np.linalg.det(coeficientes)
print(determinante)
# se comprueba que que sale error porque la matriz es no invertible.

0.0


### Pregunta 8:
a) Crea un array de forma (4, 4, 4) con números enteros aleatorios entre 0 y 100.
b) Calcula la suma a lo largo del eje 0, obteniendo un array de forma (4, 4).
c) Calcula el promedio a lo largo del eje 1, obteniendo un array de forma (4, 4).
d) Reestructura el array original en una nueva forma de (8, 8) sin perder datos.


In [22]:


# a)
array = np.random.randint(0, 101, (4, 4, 4))

# b)
suma_eje_cero = np.sum(array, axis=0)

# c)
promedio_eje1 = np.mean(array, axis=1)

# d)
array_reestructurado = array.reshape(8, 8)

print("Array original (4, 4, 4):\n", array)
print("Suma a lo largo del eje 0 (4, 4):\n", suma_eje_cero)
print("Promedio a lo largo del eje 1 (4, 4):\n", promedio_eje1)
print("Array reestructurado (8, 8):\n", array_reestructurado)


Array original (4, 4, 4):
 [[[52 60 59 87]
  [12 12 44 69]
  [14 61 39 65]
  [97 73  0 36]]

 [[47 64 30  9]
  [97  1 13 45]
  [40 23 22 66]
  [35 47 20 39]]

 [[ 1 62 55 22]
  [ 9 33 93 46]
  [63 79  2 78]
  [87  6 54 38]]

 [[55 28 82 13]
  [54 18 88 86]
  [23  7  3 32]
  [14 74 12  3]]]
Suma a lo largo del eje 0 (4, 4):
 [[155 214 226 131]
 [172  64 238 246]
 [140 170  66 241]
 [233 200  86 116]]
Promedio a lo largo del eje 1 (4, 4):
 [[43.75 51.5  35.5  64.25]
 [54.75 33.75 21.25 39.75]
 [40.   45.   51.   46.  ]
 [36.5  31.75 46.25 33.5 ]]
Array reestructurado (8, 8):
 [[52 60 59 87 12 12 44 69]
 [14 61 39 65 97 73  0 36]
 [47 64 30  9 97  1 13 45]
 [40 23 22 66 35 47 20 39]
 [ 1 62 55 22  9 33 93 46]
 [63 79  2 78 87  6 54 38]
 [55 28 82 13 54 18 88 86]
 [23  7  3 32 14 74 12  3]]


### Pregunta 9:
Se define una secuencia de números donde cada elemento es el factorial del índice correspondiente.
Formalmente:
a) Usando NumPy, crea un array que contenga los primeros 10 elementos de esta secuencia sin utilizar bucles
explícitos.
b) Calcula la suma de todos los elementos del array creado.
c) Dado que los factoriales pueden ser números muy grandes, cambia el tipo de datos del array a object para
manejar enteros arbitrariamente grandes y recalcula la suma.


In [23]:
import numpy as np

# a)
indices = np.arange(10)
factoriales = np.array([np.prod(np.arange(1, i + 1)) for i in indices])

# b)
suma_factoriales = np.sum(factoriales)

# c)
factoriales_object = factoriales.astype(object)
suma_factoriales_object = np.sum(factoriales_object)


print("Factoriales (primeros 10 elementos):", factoriales)
print("Suma de factoriales (int64):", suma_factoriales)
print("Suma de factoriales (object):", suma_factoriales_object)



Factoriales (primeros 10 elementos): [     1      1      2      6     24    120    720   5040  40320 362880]
Suma de factoriales (int64): 409114
Suma de factoriales (object): 409114


### Pregunta 10:
a) Simula un conjunto de datos que represente las alturas (en cm) de 500 personas, siguiendo una distribución
normal con media 170 y desviación estándar 10.
c) Encuentra cuántas personas miden más de 180 cm y menos de 160 cm.
d) Normaliza los datos de altura para que tengan media 0 y desviación estándar 1

In [24]:
# a)
media = 170
desviacion_estandar = 10
numero_personas = 500
alturas = np.random.normal(media, desviacion_estandar, numero_personas)

# c)
mas_180 = np.sum(alturas > 180)
menos_160 = np.sum(alturas < 160)

# d)
alturas_normalizadas = (alturas - alturas.mean()) / alturas.std()

print("Número de personas > 180 cm:", mas_180)
print("Número de personas < 160 cm:", menos_160)
print("Alturas normalizadas (primeros 10 elementos):", alturas_normalizadas[:10])


Número de personas > 180 cm: 73
Número de personas < 160 cm: 96
Alturas normalizadas (primeros 10 elementos): [ 1.59876847 -0.37091863  0.31287617  0.57881424  0.26727005  0.85939134
  0.02850262 -0.67649589 -0.1923522   1.118562  ]
