<a href="https://colab.research.google.com/github/RodrigoGuedesDP/Programacion_101/blob/main/01_Introduccion_a_Python/03_Estructuras_de_datos_parte2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


<h1 align=center><font size = 5>ESTRUCTURAS DE DATOS - PARTE 2
</font></h1>

---


**Tabla de Contenidos**

- Diccionarios
- Sets
- Matrices

---

## 1. Diccionarios

**Concepto:**

Un diccionario es una estructura de datos que almacena pares clave-valor. Las claves deben ser únicas y se utilizan para acceder a los valores asociados.

### Ejemplo 1.1: Creación de Diccionarios y Acceso a Elementos


In [ ]:
# Crear un diccionario
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
print(persona)

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}


In [ ]:
# Acceder a un valor
print("Nombre:", persona['nombre'])
print("Ciudad:", persona.get('ciudad'))
#la sentencia get permite lo mismo que el indexado


In [ ]:

# Añadir un nuevo par clave-valor
persona['profesion'] = 'Ingeniera'
print(persona)



{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima', 'profesion': 'Ingeniera'}


In [ ]:
# Eliminar un par clave-valor
del persona['ciudad']
print(persona)
# se elimina tanto la clave como el valor

{'nombre': 'Ana', 'edad': 30, 'profesion': 'Ingeniera'}


### Ejemplo 1.2: Métodos Útiles de Diccionarios


In [ ]:
# Obtener todas las claves
print(persona.keys())
# el formato que devuelve no es una lista, es un dict_keys, que es como un subespacio de un diccionario.
#en python es posible transformarlo a lista
list(persona.keys())
list(persona.values())


dict_keys(['nombre', 'edad', 'profesion'])


['Ana', 30, 'Ingeniera']

In [ ]:
# Obtener todos los valores
print(persona.values())


dict_values(['Ana', 30, 'Ingeniera'])


In [ ]:
persona['edad'] = 30
print(persona)



{'nombre': 'Ana', 'edad': 30, 'profesion': 'Ingeniera'}


In [ ]:
#imprimir el listado
my_list = []

for key in persona.keys():
  my_list.append(key)
  my_list.append(persona[key])

  print(my_list)

['nombre', 'Ana']
['nombre', 'Ana', 'edad', 30]
['nombre', 'Ana', 'edad', 30, 'profesion', 'Ingeniera']


In [ ]:
my_list = []
tipotupla = persona.items()
print(tipotupla)
#vemos que aca devuelve el dict_items
type(tipotupla)

dict_items([('nombre', 'Ana'), ('edad', 30), ('profesion', 'Ingeniera')])


dict_items

In [ ]:
my_list = []

for item in persona.items():
  my_list += list(item)

  #con este metodo puedo convertir el diccionario en una lista



['nombre', 'Ana']
['nombre', 'Ana', 'edad', 30]
['nombre', 'Ana', 'edad', 30, 'profesion', 'Ingeniera']


In [ ]:
#porque no se puede hacer directamente del diccionario a lista, solo toma las keys
lista = list(persona)
print(lista)

['nombre', 'edad', 'profesion']


In [ ]:
print(my_list)

['nombre', 'Ana', 'edad', 30, 'profesion', 'Ingeniera']


In [ ]:
# Comprobar si una clave existe en el diccionario
if 'edad' in persona:
    print("La clave 'edad' está en el diccionario.")


### Ejercicio 1: Trabajando con Diccionarios

- Crea un diccionario que contenga información sobre un automóvil (marca, modelo, año, color).
- Accede a cada valor usando su clave.
- Añade una clave para el precio del automóvil.
- Elimina la clave del color del automóvil y muestra el diccionario actualizado.
- Usa keys() y values() para imprimir las claves y valores del diccionario.



In [27]:
automovil = { "marca": "Audi", "modelo": "Q7", "año": 2020, "color": "negro"}
automovil["marca"]
automovil["modelo"]
automovil["año"]
automovil["color"]
automovil["precio"] = 30_000
del automovil["color"]
print(automovil)
print(automovil.keys())
print(automovil.values())


{'marca': 'Audi', 'modelo': 'Q7', 'año': 2020, 'precio': 30000}
dict_keys(['marca', 'modelo', 'año', 'precio'])
dict_values(['Audi', 'Q7', 2020, 30000])


In [43]:
#Ejemplo

notas = {"Rodrigo": 20, "Hugo": 18, "Sebastian": 17}
for x, y in notas.items():
  print(f"La nota de {x} es {y}")

La nota de Rodrigo es 20
La nota de Hugo es 18
La nota de Sebastian es 17


## 2. Sets

Los sets son colecciones de elementos únicos y desordenados. Son útiles para eliminar duplicados o realizar operaciones matemáticas como intersección y unión.

In [34]:
#Con este metodo podemos quitar duplicados de manera rapida conviertiendolo en set y luego conviertiendolo en lista.
my_list = ["var1", "var2", "var2"]
list(set(my_list))


['var2', 'var1']

### Ejemplo 2.1: Creación y Modificación de Sets

In [35]:
# Crear un set
numeros = {1, 2, 3, 4, 5}
print(numeros)


{1, 2, 3, 4, 5}


In [36]:
# Añadir elementos
numeros.add(6)
print(numeros)


{1, 2, 3, 4, 5, 6}


In [37]:
# Eliminar un elemento
numeros.remove(3)
print(numeros)


{1, 2, 4, 5, 6}


### Ejemplo 2.2: Operaciones de Conjuntos


In [39]:
# Crear otro set
otro_set = {4, 5, 6, 7}

In [40]:
# Unión de sets (todos los elementos)
union = numeros.union(otro_set)
print("Unión:", union)
#los datos repetidos no los agrega.


Unión: {1, 2, 4, 5, 6, 7}


In [41]:
# Intersección de sets (elementos comunes)
interseccion = numeros.intersection(otro_set)
print("Intersección:", interseccion)
#interseccion va a ser la mas usada. Poruqe no es tan sencillo de resolver con listas y tuplas.

Intersección: {4, 5, 6}


### Ejercicio 2: Operaciones con Sets

- Crea dos sets de números: uno con números del 1 al 10 y otro con números del 5 al 15.
- Encuentra la intersección y unión de ambos sets.
- Elimina un número del primer set.
- Usa un set para almacenar los nombres de tus amigos. Asegúrate de que no haya duplicados.

## 3. Matrices

En Python, las matrices pueden representarse como listas de listas. Para manipular matrices más avanzadas y realizar cálculos eficientes, utilizamos la librería NumPy.

### Ejemplo 3.1: Matrices con Listas de Listas


In [48]:
# Crear una matriz 3x3 con listas anidadas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matriz)
#Esta no es la mejor forma de crear matrices, porque luego no podre multiplicar ni sumar listas. Es mejor usar NumPy

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [45]:
# Acceder a elementos de la matriz
print("Elemento en [1][1]:", matriz[1][1])
#mantiene el indexado basado en 0.

Elemento en [1][1]: 5


In [46]:
# Modificar un elemento
matriz[2][0] = 10
print(matriz)

[[1, 2, 3], [4, 5, 6], [10, 8, 9]]


### Ejemplo 3.2: Manipulación de Matrices con NumPy


In [47]:
import numpy as np

# Crear una matriz 3x3 con NumPy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matriz_np)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
#tambien se puede con la matriz anterior creada

matriz_np2 = np.array(matriz)
print(matriz_np2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
# Sumar 10 a cada elemento
print(matriz_np + 10)



[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [59]:
#crear matriz identidad

identidad = np.identity(3)

In [57]:
#crear matriz de ceros que sea 3x2. Por eso necesito 2 inputs.
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [58]:
#crear matrices de 1.
np.ones((1,3))

array([[1., 1., 1.]])

In [62]:
#Como hallar la traza como vector
np.diag(identidad)
# la suma de la traza
sum(np.diag(identidad))
#con trace
np.trace(identidad)

3.0

In [54]:
#se podemos preguntar el tamano con shape
matriz_np2.shape
matriz_2 = np.array([
    [1, 2, 3]
  ])
matriz_2.shape
# el tamano es 1 fila y 3 columnas


(1, 3)

In [55]:
#Transpocision de matrices
matriz_np2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [51]:
# Multiplicar cada elemento por 2
print(matriz_np * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [69]:
#Crear una matriz aleatoria con numeros reales
np.random.rand(1, 3)
#con numeros enteros, se indica el rango de valores y luego el orden de la matriz
np.random.randint(1, 100, (3,3))

array([[23,  7, 58],
       [66,  7, 19],
       [80, 51, 50]])

In [68]:
#Como sacar inversa de una matriz
np.linalg.inv(np.random.randint(1, 100, (3, 3)))

array([[-0.17241897,  0.6144958 , -0.54636855],
       [ 0.14165666, -0.43697479,  0.38535414],
       [ 0.09243697, -0.35294118,  0.32773109]])

### Ejercicio 3: Operaciones con Matrices

- Crea una matriz 3x3 usando listas de listas.
- Modifica un valor de la matriz y muestra la matriz actualizada.
- Usa NumPy para crear una matriz 4x4 con números aleatorios enteros.
- Realiza una operación de suma con la matriz (suma 5 a cada elemento).
- Multiplica los elementos de la matriz por 2 usando NumPy.

## 4. Desafío


Eres el encargado de un almacén de productos electrónicos. Tienes un registro de ventas semanales para teléfonos, laptops y tabletas. Necesitas analizar las ventas para mejorar la gestión.

- Crea tres listas: una para teléfonos, otra para laptops y otra para tabletas con las ventas de cada día durante una semana.
- Usa slicing para obtener las ventas de los últimos 3 días de cada producto.
- Usa listas por comprensión para calcular el total de ventas de cada producto y el promedio de ventas diarias.
- Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5.

Instrucciones:
Usa sum() y len() para calcular el total de ventas y el promedio.
Clasifica las ventas usando listas por comprensión.

---

# Gracias por completar este laboratorio!

---