<a href="https://colab.research.google.com/github/RodrigoGuedesDP/Programacion_101/blob/main/01_Introduccion_a_Python/03_Estructuras_de_datos_parte2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


<h1 align=center><font size = 5>ESTRUCTURAS DE DATOS - PARTE 2
</font></h1>

---


**Tabla de Contenidos**

- Diccionarios
- Sets
- Matrices

---

## 1. Diccionarios

**Concepto:**

Un diccionario es una estructura de datos que almacena pares clave-valor. Las claves deben ser únicas y se utilizan para acceder a los valores asociados.

### Ejemplo 1.1: Creación de Diccionarios y Acceso a Elementos


In [8]:
# Crear un diccionario
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
print(persona)
print(persona.items())
print(list(persona.items()))

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
dict_items([('nombre', 'Ana'), ('edad', 30), ('ciudad', 'Lima')])
[('nombre', 'Ana'), ('edad', 30), ('ciudad', 'Lima')]


In [ ]:
# Acceder a un valor
print("Nombre:", persona['nombre'])
print("Ciudad:", persona.get('ciudad'))
#la sentencia get permite lo mismo que el indexado


In [3]:

# Añadir un nuevo par clave-valor
persona['profesion'] = 'Ingeniera'
print(persona)
persona["club"] = "Alianza Lima"
print(persona)


{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima', 'profesion': 'Ingeniera'}
{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima', 'profesion': 'Ingeniera', 'club': 'Alianza Lima'}


In [ ]:
# Eliminar un par clave-valor
del persona['ciudad']
print(persona)
# se elimina tanto la clave como el valor

{'nombre': 'Ana', 'edad': 30, 'profesion': 'Ingeniera'}


### Ejemplo 1.2: Métodos Útiles de Diccionarios


In [4]:
# Obtener todas las claves
print(persona.keys())
# el formato que devuelve no es una lista, es un dict_keys, que es como un subespacio de un diccionario.
#en python es posible transformarlo a lista
list(persona.keys())
list(persona.values())


dict_keys(['nombre', 'edad', 'ciudad', 'profesion', 'club'])


['Ana', 30, 'Lima', 'Ingeniera', 'Alianza Lima']

In [5]:
# Obtener todos los valores
print(persona.values())


dict_values(['Ana', 30, 'Lima', 'Ingeniera', 'Alianza Lima'])


In [6]:
persona['edad'] = 30
print(persona)



{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima', 'profesion': 'Ingeniera', 'club': 'Alianza Lima'}


In [ ]:
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
my_list = []

for key in persona.keys():
  my_list.append(key)
  my_list.append(persona[key])

  print(my_list)

['nombre', 'Ana']
['nombre', 'Ana', 'edad', 30]
['nombre', 'Ana', 'edad', 30, 'ciudad', 'Lima']


In [ ]:
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
my_list = []
tipotupla = persona.items()
print(tipotupla)
for x, y in tipotupla:
  my_list.append(x)
  my_list.append(y)
  print(my_list)

#vemos que aca devuelve el dict_items
type(tipotupla)


dict_items([('nombre', 'Ana'), ('edad', 30), ('ciudad', 'Lima')])
['nombre', 'Ana']
['nombre', 'Ana', 'edad', 30]
['nombre', 'Ana', 'edad', 30, 'ciudad', 'Lima']


dict_items

In [9]:
#Otra forma segun GPT
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}

my_list = []

for key, value in persona.items():
    my_list.append(key)
    my_list.append(value)

print(my_list)

['nombre', 'Ana', 'edad', 30, 'ciudad', 'Lima']


In [ ]:
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
my_list = []

for item in persona.items():
  my_list += list(item)

  #con este metodo puedo convertir el diccionario en una lista
  print(my_list)



['nombre', 'Ana']
['nombre', 'Ana', 'edad', 30]
['nombre', 'Ana', 'edad', 30, 'ciudad', 'Lima']


In [ ]:
#porque no se puede hacer directamente del diccionario a lista, solo toma las keys
lista = list(persona)
print(lista)

['nombre', 'edad', 'profesion']


In [ ]:
print(my_list)

['nombre', 'Ana', 'edad', 30, 'profesion', 'Ingeniera']


In [ ]:
# Comprobar si una clave existe en el diccionario
if 'edad' in persona:
    print("La clave 'edad' está en el diccionario.")


### Ejercicio 1: Trabajando con Diccionarios

- Crea un diccionario que contenga información sobre un automóvil (marca, modelo, año, color).
- Accede a cada valor usando su clave.
- Añade una clave para el precio del automóvil.
- Elimina la clave del color del automóvil y muestra el diccionario actualizado.
- Usa keys() y values() para imprimir las claves y valores del diccionario.



In [ ]:
automovil = { "marca": "Audi", "modelo": "Q7", "año": 2020, "color": "negro"}
automovil["marca"]
automovil["modelo"]
automovil["año"]
automovil["color"]
automovil["precio"] = 30_000
del automovil["color"]
print(automovil)
print(automovil.keys())
print(automovil.values())


{'marca': 'Audi', 'modelo': 'Q7', 'año': 2020, 'precio': 30000}
dict_keys(['marca', 'modelo', 'año', 'precio'])
dict_values(['Audi', 'Q7', 2020, 30000])


In [ ]:
#Ejemplo

notas = {"Rodrigo": 20, "Hugo": 18, "Sebastian": 17}
for x, y in notas.items():
  print(f"La nota de {x} es {y}")

La nota de Rodrigo es 20
La nota de Hugo es 18
La nota de Sebastian es 17


## 2. Sets

Los sets son colecciones de elementos únicos y desordenados. Son útiles para eliminar duplicados o realizar operaciones matemáticas como intersección y unión.

In [ ]:
#Con este metodo podemos quitar duplicados de manera rapida conviertiendolo en set y luego conviertiendolo en lista.
my_list = ["var1", "var2", "var2"]
list(set(my_list))


['var2', 'var1']

### Ejemplo 2.1: Creación y Modificación de Sets

In [10]:
# Crear un set
numeros = {1, 2, 3, 4, 5}
print(numeros)


{1, 2, 3, 4, 5}


In [ ]:
# Añadir elementos
numeros.add(6)
print(numeros)


{1, 2, 3, 4, 5, 6}


In [ ]:
# Eliminar un elemento
numeros.remove(3)
print(numeros)


{1, 2, 4, 5, 6}


### Ejemplo 2.2: Operaciones de Conjuntos


In [11]:
# Crear otro set
otro_set = {4, 5, 6, 7}

In [12]:
# Unión de sets (todos los elementos)
union = numeros.union(otro_set)
print("Unión:", union)
#los datos repetidos no los agrega.


Unión: {1, 2, 3, 4, 5, 6, 7}


In [ ]:
# Intersección de sets (elementos comunes)
interseccion = numeros.intersection(otro_set)
print("Intersección:", interseccion)
#interseccion va a ser la mas usada. Poruqe no es tan sencillo de resolver con listas y tuplas.

Intersección: {4, 5}


### Ejercicio 2: Operaciones con Sets

- Crea dos sets de números: uno con números del 1 al 10 y otro con números del 5 al 15.
- Encuentra la intersección y unión de ambos sets.
- Elimina un número del primer set.
- Usa un set para almacenar los nombres de tus amigos. Asegúrate de que no haya duplicados.

In [14]:
set1 = set(range(1, 11))
set2 = set(range(5, 16))
interseccion = set1.intersection(set2)
union = set1.union(set2)
print(interseccion, union)


{5, 6, 7, 8, 9, 10} {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}


## 3. Matrices

En Python, las matrices pueden representarse como listas de listas. Para manipular matrices más avanzadas y realizar cálculos eficientes, utilizamos la librería NumPy.

### Ejemplo 3.1: Matrices con Listas de Listas


In [15]:
# Crear una matriz 3x3 con listas anidadas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matriz)
#Esta no es la mejor forma de crear matrices, porque luego no podre multiplicar ni sumar listas. Es mejor usar NumPy

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [16]:
# Acceder a elementos de la matriz
print("Elemento en [1][1]:", matriz[1][1])
#mantiene el indexado basado en 0.

Elemento en [1][1]: 5


In [ ]:
# Modificar un elemento
matriz[2][0] = 10
print(matriz)

[[1, 2, 3], [4, 5, 6], [10, 8, 9]]


### Ejemplo 3.2: Manipulación de Matrices con NumPy


In [ ]:
import numpy as np

# Crear una matriz 3x3 con NumPy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matriz_np)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#tambien se puede con la matriz anterior creada

matriz_np2 = np.array(matriz)
print(matriz_np2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Sumar 10 a cada elemento
print(matriz_np + 10)



[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [18]:
#crear matriz identidad
import numpy as np
identidad = np.identity(3)
identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#crear matriz de ceros que sea 3x2. Por eso necesito 2 inputs.
np.zeros((3, 2))
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#crear matrices de 1.
np.ones((1,3))

array([[1., 1., 1.]])

In [21]:
#Como hallar la traza como vector
print(np.diag(identidad))
# la suma de la traza
print(sum(np.diag(identidad)))
#con trace
print(np.trace(identidad))

[1. 1. 1.]
3.0
3.0


In [ ]:
#ejemplo hallar el vector traza
import numpy as np

matriz_unos = np.ones((3,3))
vector_diagonal = np.diag(matriz_unos)
print(matriz_unos)
print(vector_diagonal)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1.]


In [ ]:
#se podemos preguntar el tamano con shape
matriz_np2.shape
matriz_2 = np.array([
    [1, 2, 3]
  ])
matriz_2.shape
# el tamano es 1 fila y 3 columnas


(1, 3)

In [ ]:
#Transpocision de matrices
matriz_np2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# Multiplicar cada elemento por 2
print(matriz_np * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
#Crear una matriz aleatoria con numeros reales
np.random.rand(1, 3)
#con numeros enteros, se indica el rango de valores y luego el orden de la matriz
np.random.randint(1, 100, (3,3))

array([[23,  7, 58],
       [66,  7, 19],
       [80, 51, 50]])

In [ ]:
#Como sacar inversa de una matriz
np.linalg.inv(np.random.randint(1, 100, (3, 3)))

array([[-0.17241897,  0.6144958 , -0.54636855],
       [ 0.14165666, -0.43697479,  0.38535414],
       [ 0.09243697, -0.35294118,  0.32773109]])

### Ejercicio 3: Operaciones con Matrices

- Crea una matriz 3x3 usando listas de listas.
- Modifica un valor de la matriz y muestra la matriz actualizada.
- Usa NumPy para crear una matriz 4x4 con números aleatorios enteros.
- Realiza una operación de suma con la matriz (suma 5 a cada elemento).
- Multiplica los elementos de la matriz por 2 usando NumPy.

In [27]:
matriz_3 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
matriz_3[1][1] = 20
print(matriz_3)
import numpy as np

matriz_4 = np.random.randint(1, 20, (4,4))
matriz_4 + 5
print(matriz_4)
print(matriz_4 + 5)


[[1, 2, 3], [4, 20, 6], [7, 8, 9]]
[[11 12 14  6]
 [13 15 12  2]
 [ 8  8 10 13]
 [10  7 14 19]]
[[16 17 19 11]
 [18 20 17  7]
 [13 13 15 18]
 [15 12 19 24]]


## 4. Desafío


Eres el encargado de un almacén de productos electrónicos. Tienes un registro de ventas semanales para teléfonos, laptops y tabletas. Necesitas analizar las ventas para mejorar la gestión.

- Crea tres listas: una para teléfonos, otra para laptops y otra para tabletas con las ventas de cada día durante una semana.
- Usa slicing para obtener las ventas de los últimos 3 días de cada producto.
- Usa listas por comprensión para calcular el total de ventas de cada producto y el promedio de ventas diarias.
- Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5.

Instrucciones:
Usa sum() y len() para calcular el total de ventas y el promedio.
Clasifica las ventas usando listas por comprensión.

In [37]:
#Creamos las 3 listas de ventas semanales

ventas_telefonos = [5, 3, 4, 4, 2, 1, 2]
ventas_laptops = [6, 7, 11, 7, 5, 10, 14]
ventas_tabletas = [8, 9, 11, 15, 11, 14, 10]

ventas_telefonos_ultimos_3_dias = ventas_telefonos[-3:]
ventas_laptops_ultimos_3_dias = ventas_laptops[-3:]
ventas_tabletas_ultimos_3_dias = ventas_tabletas[-3:]

ventas_semanales = {"ventas telefonos" : ventas_telefonos,"ventas laptops": ventas_laptops, "ventas tabletas": ventas_tabletas}
total_ventas = {}
promedio_ventas = {}
clasificacion_ventas = {}
for key, value in ventas_semanales.items():
  total_ventas["Total de " + key] = sum(value)
  promedio = round(sum(value)/len(value), 2)
  promedio_ventas["Promedio de " + key] = promedio
  clasificacion_ventas["Clasificacion " + key] = "Ventas altas" if promedio >= 5 else "Ventas bajas"

print(total_ventas)
print(promedio_ventas)
print(clasificacion_ventas)
print(ventas_telefonos_ultimos_3_dias)

{'Total de ventas telefonos': 21, 'Total de ventas laptops': 60, 'Total de ventas tabletas': 78}
{'Promedio de ventas telefonos': 3.0, 'Promedio de ventas laptops': 8.57, 'Promedio de ventas tabletas': 11.14}
{'Clasificacion ventas telefonos': 'Ventas bajas', 'Clasificacion ventas laptops': 'Ventas altas', 'Clasificacion ventas tabletas': 'Ventas altas'}
[2, 1, 2]


---

# Gracias por completar este laboratorio!

---